# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "pub" # This specifies that Dependabot should look for Dart packages
    directory: "/" # The root directory where pubspec.yaml is located
    schedule:
      interval: "weekly" # Check for updates weekly
